//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 04:12:57 PM GMT 
//


package plataforma.modelointerno;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the plataforma.modelointerno package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: plataforma.modelointerno
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link SearchByTermResponse }
     * 
     */
    public SearchByTermResponse createSearchByTermResponse() {
        return new SearchByTermResponse();
    }

    /**
     * Create an instance of {@link SearchByTermRequest }
     * 
     */
    public SearchByTermRequest createSearchByTermRequest() {
        return new SearchByTermRequest();
    }

    /**
     * Create an instance of {@link ListRepositoriesResponse }
     * 
     */
    public ListRepositoriesResponse createListRepositoriesResponse() {
        return new ListRepositoriesResponse();
    }

    /**
     * Create an instance of {@link Repository }
     * 
     */
    public Repository createRepository() {
        return new Repository();
    }

    /**
     * Create an instance of {@link GetResultRequest }
     * 
     */
    public GetResultRequest createGetResultRequest() {
        return new GetResultRequest();
    }

    /**
     * Create an instance of {@link GetResultResponse }
     * 
     */
    public GetResultResponse createGetResultResponse() {
        return new GetResultResponse();
    }

    /**
     * Create an instance of {@link SearchByBoxResponse }
     * 
     */
    public SearchByBoxResponse createSearchByBoxResponse() {
        return new SearchByBoxResponse();
    }

    /**
     * Create an instance of {@link ListRepositoriesRequest }
     * 
     */
    public ListRepositoriesRequest createListRepositoriesRequest() {
        return new ListRepositoriesRequest();
    }

    /**
     * Create an instance of {@link SearchByBoxRequest }
     * 
     */
    public SearchByBoxRequest createSearchByBoxRequest() {
        return new SearchByBoxRequest();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link ExtraProperty }
     * 
     */
    public ExtraProperty createExtraProperty() {
        return new ExtraProperty();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link ValueField }
     * 
     */
    public ValueField createValueField() {
        return new ValueField();
    }

    /**
     * Create an instance of {@link RelationField }
     * 
     */
    public RelationField createRelationField() {
        return new RelationField();
    }

    /**
     * Create an instance of {@link RelationLocations }
     * 
     */
    public RelationLocations createRelationLocations() {
        return new RelationLocations();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link TimeSpan }
     * 
     */
    public TimeSpan createTimeSpan() {
        return new TimeSpan();
    }

    /**
     * Create an instance of {@link LanguageString }
     * 
     */
    public LanguageString createLanguageString() {
        return new LanguageString();
    }

    /**
     * Create an instance of {@link Result.CreatedIn }
     * 
     */
    public Result.CreatedIn createResultCreatedIn() {
        return new Result.CreatedIn();
    }

}
