//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 01:39:11 AM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "Plataforma/ModeloInterno", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package plataforma.modelointerno;
