//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 03:47:49 PM GMT 
//


package plataforma.modelointerno;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="repositories" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ignoreExtraProperties" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="disableRelation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="disableCombine" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "term",
    "repositories",
    "ignoreExtraProperties",
    "disableRelation",
    "disableCombine"
})
@XmlRootElement(name = "searchByTermRequest")
public class SearchByTermRequest {

    @XmlElement(required = true)
    protected String term;
    @XmlElement(type = Integer.class)
    protected List<Integer> repositories;
    @XmlElement(defaultValue = "false")
    protected boolean ignoreExtraProperties;
    @XmlElement(defaultValue = "false")
    protected boolean disableRelation;
    @XmlElement(defaultValue = "false")
    protected boolean disableCombine;

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the repositories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repositories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepositories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getRepositories() {
        if (repositories == null) {
            repositories = new ArrayList<Integer>();
        }
        return this.repositories;
    }

    /**
     * Gets the value of the ignoreExtraProperties property.
     * 
     */
    public boolean isIgnoreExtraProperties() {
        return ignoreExtraProperties;
    }

    /**
     * Sets the value of the ignoreExtraProperties property.
     * 
     */
    public void setIgnoreExtraProperties(boolean value) {
        this.ignoreExtraProperties = value;
    }

    /**
     * Gets the value of the disableRelation property.
     * 
     */
    public boolean isDisableRelation() {
        return disableRelation;
    }

    /**
     * Sets the value of the disableRelation property.
     * 
     */
    public void setDisableRelation(boolean value) {
        this.disableRelation = value;
    }

    /**
     * Gets the value of the disableCombine property.
     * 
     */
    public boolean isDisableCombine() {
        return disableCombine;
    }

    /**
     * Sets the value of the disableCombine property.
     * 
     */
    public void setDisableCombine(boolean value) {
        this.disableCombine = value;
    }

}
